
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres.kmcjsypzhmgncmbnwooc:WuKAkjQCJmhtrbGz@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true
    env_file:
      - .env
#    depends_on:
#      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

#  postgres:
#    image: postgres:15
#    environment:
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#      - ./src/database/migrations:/docker-entrypoint-initdb.d
#    restart: unless-stopped

volumes:
  postgres_data:
